import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Providers  from "./redux/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ur's Store",
  description: "Generated by Utkarsh Garg",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
        <div className="mx-auto my-0 max-w-6xl px-8">
          <NavBar/>
        </div>
        {children}
        <Footer/>
      </Providers>
      </body>
    </html>
  );
}
